-- 文件用途：创建 KuaiRec 原始数据在 MySQL 中的落地表，适合在 MySQL Workbench 中手动建表后再执行导入。

CREATE TABLE IF NOT EXISTS kuairec_small_matrix (
    user_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    play_duration BIGINT,
    video_duration BIGINT,
    time VARCHAR(32),
    date DOUBLE,
    timestamp DOUBLE,
    watch_ratio DOUBLE,
    INDEX idx_kuairec_small_user_id (user_id),
    INDEX idx_kuairec_small_video_id (video_id),
    INDEX idx_kuairec_small_timestamp (timestamp)
);

CREATE TABLE IF NOT EXISTS kuairec_big_matrix (
    user_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    play_duration BIGINT,
    video_duration BIGINT,
    time VARCHAR(32),
    date DOUBLE,
    timestamp DOUBLE,
    watch_ratio DOUBLE,
    INDEX idx_kuairec_big_user_id (user_id),
    INDEX idx_kuairec_big_video_id (video_id),
    INDEX idx_kuairec_big_timestamp (timestamp)
);

CREATE TABLE IF NOT EXISTS kuairec_user_features (
    user_id BIGINT NOT NULL,
    user_active_degree VARCHAR(64),
    is_lowactive_period INT,
    is_live_streamer INT,
    is_video_author INT,
    follow_user_num BIGINT,
    follow_user_num_range VARCHAR(64),
    fans_user_num BIGINT,
    fans_user_num_range VARCHAR(64),
    friend_user_num BIGINT,
    friend_user_num_range VARCHAR(64),
    register_days BIGINT,
    register_days_range VARCHAR(64),
    onehot_feat0 INT,
    onehot_feat1 INT,
    onehot_feat2 INT,
    onehot_feat3 INT,
    onehot_feat4 INT,
    onehot_feat5 INT,
    onehot_feat6 INT,
    onehot_feat7 INT,
    onehot_feat8 INT,
    onehot_feat9 INT,
    onehot_feat10 INT,
    onehot_feat11 INT,
    onehot_feat12 INT,
    onehot_feat13 INT,
    onehot_feat14 INT,
    onehot_feat15 INT,
    onehot_feat16 INT,
    onehot_feat17 INT,
    INDEX idx_kuairec_user_features_user_id (user_id),
    INDEX idx_kuairec_user_active_degree (user_active_degree)
);

CREATE TABLE IF NOT EXISTS kuairec_item_daily_features (
    video_id BIGINT NOT NULL,
    date BIGINT,
    author_id BIGINT,
    video_type VARCHAR(64),
    upload_dt VARCHAR(64),
    upload_type VARCHAR(64),
    visible_status VARCHAR(64),
    video_duration DOUBLE,
    video_width BIGINT,
    video_height BIGINT,
    music_id BIGINT,
    video_tag_id BIGINT,
    video_tag_name VARCHAR(255),
    show_cnt BIGINT,
    show_user_num BIGINT,
    play_cnt BIGINT,
    play_user_num BIGINT,
    play_duration BIGINT,
    complete_play_cnt BIGINT,
    complete_play_user_num BIGINT,
    valid_play_cnt BIGINT,
    valid_play_user_num BIGINT,
    long_time_play_cnt BIGINT,
    long_time_play_user_num BIGINT,
    short_time_play_cnt BIGINT,
    short_time_play_user_num BIGINT,
    play_progress DOUBLE,
    comment_stay_duration BIGINT,
    like_cnt BIGINT,
    like_user_num BIGINT,
    click_like_cnt BIGINT,
    double_click_cnt BIGINT,
    cancel_like_cnt BIGINT,
    cancel_like_user_num BIGINT,
    comment_cnt BIGINT,
    comment_user_num BIGINT,
    direct_comment_cnt BIGINT,
    reply_comment_cnt BIGINT,
    delete_comment_cnt BIGINT,
    delete_comment_user_num BIGINT,
    comment_like_cnt BIGINT,
    comment_like_user_num BIGINT,
    follow_cnt BIGINT,
    follow_user_num BIGINT,
    cancel_follow_cnt BIGINT,
    cancel_follow_user_num BIGINT,
    share_cnt BIGINT,
    share_user_num BIGINT,
    download_cnt BIGINT,
    download_user_num BIGINT,
    report_cnt BIGINT,
    report_user_num BIGINT,
    reduce_similar_cnt BIGINT,
    reduce_similar_user_num BIGINT,
    collect_cnt DOUBLE,
    collect_user_num DOUBLE,
    cancel_collect_cnt DOUBLE,
    cancel_collect_user_num DOUBLE,
    INDEX idx_kuairec_item_daily_video_id (video_id),
    INDEX idx_kuairec_item_daily_date (date),
    INDEX idx_kuairec_item_daily_author_id (author_id)
);

CREATE TABLE IF NOT EXISTS kuairec_item_categories (
    video_id BIGINT NOT NULL,
    feat TEXT,
    INDEX idx_kuairec_item_categories_video_id (video_id)
);
